/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class giris_sayfasi extends javax.swing.JFrame {

    
    Connection conn;
     Statement komut;
     Connection conn2;
     Statement komut2;
     ResultSet rs;
     ResultSet rs2;
     bilgiler iste= new  bilgiler  ();
    /**
     * Creates new form giris_sayfasi
     */
    public giris_sayfasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_kadi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Kullanıcı Adı:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Şifre:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("GİRİŞ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("REHBERLİK SERVİSİ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText(" BİLGİ SİSTEMİ");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projem/rehberlkservisi.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kadi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txt_kadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:try {
            try{
              Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");
                 Statement komut = conn.createStatement();
                 
                 
                 Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
        Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");
                 Statement komut2 = conn2.createStatement();
        rs = komut.executeQuery("Select * from kullanicilar where kullanici_adi='"+txt_kadi.getText().toUpperCase()+"' AND sifre='"+txt_sifre.getText().toUpperCase()+"'");
        rs2 = komut2.executeQuery("Select * from ogrenciler where numara='"+txt_kadi.getText()+"' AND ogrencisifre='"+txt_sifre.getText().toUpperCase()+"'");
           if (rs.first()){
                if (rs.getString("kullaniciTipi").equals("mudur")) {//kullanıcı kısmının eşleşmesi
                    
                   //onaylandı ise sayfasına geçecek
                    //this.setVisible(false);
                        
                         this.dispose();
                           String ad=rs.getString("adi");
                    String soyad=rs.getString("soyadi");
                    int telefonu=rs.getInt("telefon");
                    int IDsi=rs.getInt("kullaniciID");
                    String k_adi=rs.getString("kullanici_adi");
                     iste.adi=ad;
                     iste.soyadi=soyad;
                     iste.kullanici_adi=k_adi;
                     iste.kullanici_ID=IDsi;
                     
                 
                     new mudur_ekrani().setVisible(true);
                   
                    
                    
                 
                     }
                else if (rs.getString("kullaniciTipi").equals("rehberci")) {  //kullanıcı kontrolü
                   //onaylandı ise kullanici sayfasına geçecek
                     //this.setVisible(false); 
                       this.dispose();
                        String ad=rs.getString("adi");
                    String soyad=rs.getString("soyadi");
                    int telefonu=rs.getInt("telefon");
                    int IDsi=rs.getInt("kullaniciID");
                    String k_adi=rs.getString("kullanici_adi");
                     iste.adi=ad;
                     iste.soyadi=soyad;
                     iste.kullanici_adi=k_adi;
                     iste.kullanici_ID=IDsi;
                     
                     new rehber_ekrani().setVisible(true);
               
                 }
                  
              
                
                
                } 
                else if(rs2.first()) { 
                if ((rs2.getInt("numara")==Integer.parseInt(txt_kadi.getText()))&& (rs2.getString("ogrencisifre").equals(txt_sifre.getText()))) {  //kullanıcı kontrolü
                   //onaylandı ise kullanici sayfasına geçecek
                     //this.setVisible(false); 
                       this.dispose();
                        String ad=rs2.getString("adi");
                    String soyad=rs2.getString("soyadi");
                    String TC=rs2.getString("tc");
                    
                    int ogrIDsi=rs2.getInt("ogrenciID");
                    int k_numara=rs2.getInt("numara");
                    iste.adi=ad;
                     iste.soyadi=soyad;
                     iste.ogrenci_IDsi=ogrIDsi;
                     iste.kullanici_IDsi=k_numara;
                     iste.tecem=TC;
                     
                     
                     new veli_ekrani().setVisible(true);
               
                 }
              
           else{
               // kullanıcı adı ve sifre eşleşmiyorsa yapılacak işlemler
               JOptionPane.showMessageDialog(rootPane, "kullanıcı adi veya şifre yanlış", "bilgi", 0);
                txt_kadi.setText("");
                txt_sifre.setText("");}
            }
         /* if (rs.first()) {
                if (rs.getString(1).equals("1")) {
                    adminsayfası aa=new adminsayfası();
                    aa.setVisible(true);
                    this.dispose();
                }
                else if (rs.getString(1).equals("2"))
                {
                    kullanicisayfası aa=new kullanicisayfası();
                    aa.setVisible(true);
                    this.dispose();
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "KULLANICI ADI VEYA ŞİFRE HATALI", "HATA", 0);
            }*/
        conn.close(); 
        } catch (Exception e) {    // veri tabanı hatasında ekrana gelecek hata
           System.out.println(e.getMessage());
             JOptionPane.showMessageDialog(rootPane, e.toString());
           JOptionPane.showMessageDialog(rootPane, "bağlantı hatası", "bilgi", 0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giris_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giris_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giris_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giris_sayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giris_sayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_kadi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
