/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

import java.sql.Statement;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author user
 */
public class mudur_ekrani extends javax.swing.JFrame {

    /**
     * Creates new form mudur_ekrani
     */
    private Connection conn;
    private  Statement komut;
     private  Statement pst;
    private ResultSet rs;
    private Connection con2;
    private  Statement komut2;
     private  Statement pst2;
    private ResultSet rss2;
    String gor;
    public mudur_ekrani() {
        initComponents();
        uyelerilistele();
        rehberci_goster();
        rehberci_sonuclari();
        rehberlik_sonuclari_sifirla();
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mudur_adi = new javax.swing.JTextField();
        mudur_soyadi = new javax.swing.JTextField();
        mudur_kadi = new javax.swing.JTextField();
        mudur_sifre = new javax.swing.JTextField();
        mudur_tel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rehber_adi = new javax.swing.JTextField();
        rehber_soyadi = new javax.swing.JTextField();
        rehber_kadi = new javax.swing.JTextField();
        rehber_sifre = new javax.swing.JTextField();
        rehber_tel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        rehber_adres = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rehber_ogr_durum = new javax.swing.JTable();
        rehberadi_ara = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        rehberlik_sonuclari = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adı:");

        jLabel2.setText("Soyadı:");

        jLabel3.setText("Kullanıcı Adı:");

        jLabel4.setText("Şifre:");

        jLabel5.setText("Telefon:");

        mudur_soyadi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudur_soyadiActionPerformed(evt);
            }
        });

        jButton1.setText("Güncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("yenile");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton5)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mudur_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mudur_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mudur_kadi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mudur_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mudur_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(694, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mudur_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mudur_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mudur_kadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mudur_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mudur_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Kullanıcı Bilgileri", jPanel1);

        jLabel6.setText("Adı:");

        jLabel10.setText("Soyadı:");

        jLabel11.setText("Kullanıcı Adı:");

        jLabel12.setText("Şifre:");

        jLabel13.setText("Telefon:");

        jLabel14.setText("Adres:");

        rehber_kadi.setToolTipText("");
        rehber_kadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rehber_kadiKeyReleased(evt);
            }
        });

        rehber_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rehber_telKeyReleased(evt);
            }
        });

        rehber_adres.setColumns(20);
        rehber_adres.setRows(5);
        rehber_adres.setPreferredSize(new java.awt.Dimension(120, 64));
        jScrollPane1.setViewportView(rehber_adres);

        jButton2.setText("Rehber Öğretmen Ata");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Durum"));

        rehber_ogr_durum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rehber_ogr_durum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rehber_ogr_durumMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(rehber_ogr_durum);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel17.setText("TC GİRİNİZ..!!!");

        jButton4.setText("Sil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton8.setText("Ara");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Soyada Göre");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Kullanıcı Adına Göre");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton9.setText("Yenile");
        jButton9.setToolTipText("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(rehber_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                                                .addComponent(jLabel13))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(rehber_kadi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(rehber_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rehber_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rehber_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rehberadi_ara, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton9)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rehber_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rehber_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rehber_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(rehber_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rehber_kadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(rehberadi_ara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        rehber_kadi.getAccessibleContext().setAccessibleName("");

        jTabbedPane7.addTab("Rehber Öğretmen Ata", jPanel2);

        rehberlik_sonuclari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TC Kimlik No:", "Adı", "Soyadı", "Velisi", "Sonuç"
            }
        ));
        rehberlik_sonuclari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rehberlik_sonuclariMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rehberlik_sonuclari);

        jLabel15.setText("Okul Numarası");

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
        });

        jButton3.setText("Ara");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("Yenile");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel16.setText("Adı:");

        jLabel18.setText("Soyadı:");

        jLabel19.setText("Okul Numarası:");

        jLabel20.setText("Sınıfı:");

        jLabel21.setText("Görüşme Nedeni:");

        jLabel22.setText("Görüşme Tarihi:");

        jLabel23.setText("Danışman Adı Soyadı:");

        jLabel24.setText("Görüşme Sonucu:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane4.setViewportView(jTextArea1);

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        jLabel28.setText("jLabel28");

        jLabel29.setText("jLabel29");

        jLabel30.setText("jLabel30");

        jLabel31.setText("jLabel31");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(301, 301, 301)
                        .addComponent(jButton7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27)
                                            .addComponent(jLabel28)
                                            .addComponent(jLabel29))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel30)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel32)
                .addContainerGap())
        );

        jTabbedPane7.addTab("Rehberlik Sonuçları ", jPanel3);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projem/rehberlkservisi.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("REHBERLİK SERVİSİ BİLGİ SİSTEMİ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("OKUL MÜDÜR ARAYÜZÜ");

        jButton6.setText("ÇIKIŞ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel9)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(26, 26, 26))))
            .addComponent(jTabbedPane7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addGap(38, 38, 38)))
                .addComponent(jTabbedPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mudur_soyadiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudur_soyadiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mudur_soyadiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //goster();
        
       guncellee();
      
       //goster();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        kayit();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        uyelerilistele();
        JOptionPane.showMessageDialog(rootPane,"Yenilendi");
    }//GEN-LAST:event_jButton5ActionPerformed
private void rehberci_sonuclari(){
        try {
          Class.forName("com.mysql.jdbc.Driver");
            Connection baglan = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
            Statement komut=baglan.createStatement();
            ResultSet rs1=(ResultSet) komut.executeQuery("SELECT gorusmeler.gorusmeID,ogrenciler.adi,ogrenciler.soyadi,ogrenciler.sinif,ogrenciler.numara,gorusmeler.gorusme_neden,gorusmeler.gorusme_tarih,gorusmeler.gorusme_yapan,gorusmeler.gorusme_sonuc FROM ogrenciler INNER JOIN gorusmeler ON ogrenciler.tc = gorusmeler.gorusmeTC where gorusmeler.gorusme_durumu='sonuclandi'" );
            ResultSetMetaData metaData = rs1.getMetaData();
            int kolunsayisi=metaData.getColumnCount();
            Vector vector_veriler=new Vector ();
            for(int t=0;t<kolunsayisi;t++){
            vector_veriler.addElement(metaData.getColumnLabel(t+1)); 
            }
            Vector vector_kayitlar=new Vector();
            while(rs1.next()){
                Vector vector_kayit=new Vector();
                for(int j=0;j<kolunsayisi;j++){
                    vector_kayit.addElement(rs1.getObject(j+1));
                   
                }
                vector_kayitlar.addElement(vector_kayit);
                
            }
          
          DefaultTableModel dtm=new DefaultTableModel(vector_kayitlar,vector_veriler);
          rehberlik_sonuclari.setModel(dtm);
          
          
        }
        catch(Exception hata) {
            JOptionPane.showMessageDialog(rootPane, hata.toString());
        }
    }
    
    
    private void rehberci_temizle(){
           rehber_adi.setText("");
           rehber_soyadi.setText("");
           rehber_kadi.setText("");
           rehber_sifre.setText("");
           rehber_tel.setText("");
           rehber_adres.setText("");}
    
    private void rehberci_goster(){
        try {
          Class.forName("com.mysql.jdbc.Driver");
            Connection baglan = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
            Statement komut=baglan.createStatement();
            ResultSet rs1=(ResultSet) komut.executeQuery("SELECT kullaniciID,kullanici_adi,sifre,adi,soyadi,telefon,adres FROM kullanicilar WHERE kullaniciTipi='rehberci'" );
            ResultSetMetaData metaData = rs1.getMetaData();
            int kolunsayisi=metaData.getColumnCount();
            Vector vector_veriler=new Vector ();
            for(int t=0;t<kolunsayisi;t++){
            vector_veriler.addElement(metaData.getColumnLabel(t+1)); 
            }
            Vector vector_kayitlar=new Vector();
            while(rs1.next()){
                Vector vector_kayit=new Vector();
                for(int j=0;j<kolunsayisi;j++){
                    vector_kayit.addElement(rs1.getObject(j+1));
                   
                }
                vector_kayitlar.addElement(vector_kayit);
                
            }
          
          DefaultTableModel dtm=new DefaultTableModel(vector_kayitlar,vector_veriler);
          rehber_ogr_durum.setModel(dtm);
          
          
        }
        catch(Exception hata) {
            JOptionPane.showMessageDialog(rootPane, hata.toString());
        }
    }
    
    private void rehber_ogr_durumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehber_ogr_durumMouseClicked
        // TODO add your handling code here:
        //tabloid.setText(rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 0).toString());
          rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 1).toString();
         rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 2).toString();//değerleri gerekli kutucuklara aktarıyoruz 
        rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 3).toString();
      rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 4).toString();
      rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 5).toString();
       rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(),6).toString();
        
    }//GEN-LAST:event_rehber_ogr_durumMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        rehberci_sil();
        rehberci_goster();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new giris_sayfasi().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        rehberci_sonuclari();
        rehberlik_sonuclari_sifirla();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void rehberlik_sonuclari_sifirla(){
    jTextField11.setText("");
        jLabel25.setText("");
        jLabel26.setText("");
        jLabel27.setText("");
        jLabel28.setText("");
        jLabel29.setText("");
        jLabel30.setText("");
        jLabel31.setText("");
        jTextArea1.setText("");
    
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        try {
             
             if(jRadioButton1.isSelected()){
                 String soyadi=rehberadi_ara.getText();
                 for (int i = 0; i < soyadi.length(); i++)
                {

                        if (Character.isDigit(soyadi.charAt(i)))
                        {
                                JOptionPane.showMessageDialog(rootPane,"lütfen sayı girmeyiniz");
                        }else{
                             eklenen_rehbercileri_ara(rehberadi_ara.getText());}
        }
       
           
       
              }
             else if(jRadioButton2.isSelected()){
                 String k_adi =rehberadi_ara.getText();
                 
                    for (int i = 0; i < k_adi.length(); i++)
                   {

                        if (Character.isDigit(k_adi.charAt(0)))
                        {
                            eklenen_rehbercileri_ara(rehberadi_ara.getText());
                            
                            
                                
                        }else{
                        JOptionPane.showMessageDialog(rootPane,"lütfen metin girmeyiniz");
                        }
                }
       
           
       
              }
            
            
                //aratablodoldur (ara.getText());
             // String c=jTextField2.getText();
                
        }
  catch (Exception e) {
       JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void eklenen_rehbercileri_ara(String alinan){
                String gelendeger= alinan;
        String baslik[] = new String[]{ "kullaniciID","kullanici_adi","sifre","adi","soyadi","telefon","adres"};

        try {
                 Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");
                 Statement komut = conn.createStatement();
                 pst = conn.createStatement();
                 String sorgu;
                 

                        if (Character.isDigit(gelendeger.charAt(0)))
                        {
                            
                                sorgu = "select * from kullanicilar where kullanici_adi like '%"+gelendeger+"%' and kullaniciTipi='rehberci'";
                                rs = (ResultSet) pst.executeQuery(sorgu);
                        }
                        else {
                            
                         sorgu = "select * from kullanicilar where soyadi like '%"+gelendeger+"%' and  kullaniciTipi='rehberci'";
                         rs = (ResultSet) pst.executeQuery(sorgu);
                        }
                        
        


           // String sorgu = "select * from kullanicilar where soyadi='"+gelendeger+"'";

           
            

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();
            Object data[][] = new Object[kayitsayisi][];
            int i = 0;
 
 while (rs.next()) {

                data[i] = new Object[]{
                    rs.getInt("kullaniciID"),
                    rs.getString("kullanici_adi"),
                    rs.getString("sifre"),
                    rs.getString("adi"),rs.getString("soyadi"),rs.getInt("telefon"),rs.getString("adres")};
                i++;
            }
            conn.close();
             rehber_ogr_durum.setModel(new DefaultTableModel(data, baslik));
              if(kayitsayisi==0){//kayıt bulunmuyorsa gösterir
         JOptionPane.showMessageDialog(rootPane,"İstenilen kayıt bulunmamaktadır");  }          
              
        } catch (Exception hata) {
            JOptionPane.showMessageDialog(rootPane, hata.toString());}           
    


}
    
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){

            jRadioButton2.setSelected(false);
          
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void rehberlik_sonuclariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehberlik_sonuclariMouseClicked
        // rehberlik sonuclarını tablodan hangisine tıklarsak ordaki bilgiler label lere aktarılıyor.görüşmeler tablosunun id sine göre
        jLabel32.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(), 0).toString());
       jLabel25.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(), 1).toString());
       jLabel26.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(), 2).toString());//değerleri gerekli kutucuklara aktarıyoruz 
       jLabel28.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(), 3).toString());
       jLabel27.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(), 4).toString());
       jLabel29.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(), 5).toString());
       jLabel30.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(),6).toString());
       jLabel31.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(),7).toString());
       jTextArea1.setText(rehberlik_sonuclari.getValueAt(rehberlik_sonuclari.getSelectedRow(),8).toString());
       
    }//GEN-LAST:event_rehberlik_sonuclariMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
             
             
       
           danisanlari_ara(jTextField11.getText());
       
            
                //aratablodoldur (ara.getText());
             // String c=jTextField2.getText();
                
        }
  catch (Exception e) {
       JOptionPane.showMessageDialog(rootPane, e.toString());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton2.isSelected()){

            jRadioButton1.setSelected(false);
          
        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void rehber_kadiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rehber_kadiKeyReleased
        // TODO add your handling code here:
        if(!rehber_kadi.getText().matches("[0-9]*") ) { 
             JOptionPane.showMessageDialog(rootPane, "Tc alanına harf girmeyiniz?");
        rehber_kadi.setText("");
    
    }
    }//GEN-LAST:event_rehber_kadiKeyReleased

    private void rehber_telKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rehber_telKeyReleased
        // TODO add your handling code here:
        if(!rehber_tel.getText().matches("[0-9]*") ) { 
             JOptionPane.showMessageDialog(rootPane, "Telefon alanına harf girmeyiniz?");
        rehber_tel.setText("");
    
    }
    }//GEN-LAST:event_rehber_telKeyReleased

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        // TODO add your handling code here:
         if(!jTextField11.getText().matches("[0-9]*") ) { 
             JOptionPane.showMessageDialog(rootPane, "TC alanına harf girmeyiniz?");
        jTextField11.setText("");
    
    }
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        rehberci_goster();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void danisanlari_ara(String alinan){
         //int numaramm= getir.getnumarasi();
       String gelendeger= alinan;
        String baslik[] = new String[]{ "gorusmeID","adi","soyadi","sinif","numara","gorusme_neden","gorusme_tarih","gorusme_yapan","gorusme_sonuc"};

        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
         conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");
                 komut = conn.createStatement();

            String sorgu = "select * FROM ogrenciler INNER JOIN gorusmeler ON ogrenciler.tc = gorusmeler.gorusmeTC where ogrenciler.numara like '%"+gelendeger+"%' and gorusmeler.gorusme_durumu='sonuclandi' ";

           pst = conn.createStatement();
            rs = (ResultSet) pst.executeQuery(sorgu);

            // kac tane kayit var onu buluyor
            rs.last();
            int kayitsayisi = rs.getRow();
            rs.beforeFirst();
            Object data[][] = new Object[kayitsayisi][];
            int i = 0;
 
 while (rs.next()) {

                data[i] = new Object[]{
                    rs.getInt("gorusmeID"),
                    rs.getString("adi"),
                    rs.getString("soyadi"),
                    rs.getString("sinif"),
                    rs.getInt("numara"),
                    rs.getString("gorusme_neden"),
                    rs.getString("gorusme_tarih"),
                    rs.getString("gorusme_yapan"),
                    rs.getString("gorusme_sonuc")};
                i++;
            }
            conn.close();
             rehberlik_sonuclari.setModel(new DefaultTableModel(data, baslik));
              if(kayitsayisi==0){//kayıt bulunmuyorsa gösterir
         JOptionPane.showMessageDialog(rootPane,"İstenilen kayıt bulunmamaktadır");  }          
              
        } catch (Exception hata) {
            JOptionPane.showMessageDialog(rootPane, hata.toString());}           
    


}
     private void rehberci_sil(){
    
       try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");
                 Statement komut = conn.createStatement();

              String tablodangelen = rehber_ogr_durum.getValueAt(rehber_ogr_durum.getSelectedRow(), 0).toString(); 
            /*komut.executeUpdate("INSERT INTO silinen_uyeler(numarasi,adi,soyadi,kullanici_adi,sifre,yetki,onay_durumu) values('" +
                    uye_numarasi.getText() +
                   "','" + uye_adi.getText() +
                   "','" +uye_soyadi.getText() +
                   "','" +uye_nikii.getText() +
                   "','" +uye_sifresi.getText() + "','"+uye_yetkisi.getSelectedItem()+"','onaylandi')");*/
              
            String sql = "DELETE FROM kullanicilar "
                    + "WHERE kullaniciID = " + tablodangelen;
            
            komut.executeUpdate(sql); 
            JOptionPane.showMessageDialog(rootPane,"kayıt başarıyla silindi");
        }
        catch(Exception hata){
            
            JOptionPane.showMessageDialog(rootPane, hata.toString());
            
        }
    
    }
      private void kayit(){
        try{
           
             /*Class.forName("com.mysql.jdbc.Driver");
           baglan=DriverManager.getConnection("jdbc:mysql://localhost/sekreter","root","");
           Statement EklemeKomutu=baglan.createStatement();*/
           String unvanlar ="rehberci";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
         conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");
       
        
        
         
    
         
         
   if((rehber_kadi.getText().length()==11)) { 
       
           
       getToolkit().beep();/**Girilen karakterin uzunluğu küçük eşit 3 değilse aşağıdakini yap*/
          
           Statement komut = conn.createStatement();
           komut.executeUpdate("INSERT INTO kullanicilar(kullanici_adi,sifre,adi,soyadi,telefon,adres,kullaniciTipi) values('" +
                   rehber_kadi.getText() +
                   "','" +rehber_sifre.getText() +
                   "','" +rehber_adi.getText() +
                   "','" +rehber_soyadi.getText() +
                   "','" +rehber_tel.getText() +
                   "','" +rehber_adres.getText() +
                  "','" +unvanlar+
                       "')");
           
           JOptionPane.showMessageDialog(rootPane,"Başarıyla Kayıt Tamamlandı..");
           rehberci_goster();
        rehberci_temizle();
       
        
          
    }
   else{
   JOptionPane.showMessageDialog(rootPane, "Tc'niz 11 karakter değil. Lütfen kontrol ediniz");
   
   }
       
            
            
        }catch(Exception hata){
            JOptionPane.showMessageDialog(rootPane, hata.toString());
        }
        
    }
      
      
      private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {    
    char c = evt.getKeyChar();
    if(!(Character.isDigit(c))) {  

    /** Basılan tuş rakam veya backspace veya delete değilse aşağıdakini yap*/
          JOptionPane.showMessageDialog(rootPane, "doğru");
    }
    else{
    JOptionPane.showMessageDialog(rootPane, "yanlış");
    }
   
}
      private void uyelerilistele(){
    try {
          Class.forName("com.mysql.jdbc.Driver").newInstance();
              conn =  DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik", "root","");
             komut= conn.createStatement();
             rs= komut.executeQuery("SELECT * FROM kullanicilar WHERE kullaniciTipi='mudur'" );
             ResultSetMetaData metaData = rs.getMetaData();
            int kolunsayisi=metaData.getColumnCount();
            Vector vector_veriler=new Vector ();
            for(int t=0;t<kolunsayisi;t++){
            vector_veriler.addElement(metaData.getColumnLabel(t+1)); 
            }
            Vector vector_kayitlar=new Vector();
            while(rs.next()){
              mudur_kadi.setText(rs.getString("kullanici_adi"));
           mudur_adi.setText(rs.getString("adi"));
           mudur_soyadi.setText(rs.getString("soyadi"));
           mudur_sifre.setText(rs.getString("sifre"));
           mudur_tel.setText(rs.getString("telefon"));
                
            }
          
            
          
          
        }
        catch(Exception hata) {
            JOptionPane.showMessageDialog(rootPane, hata.toString());
        }
    }
      private void goster(){
        try {
          Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik", "root","");
         System.out.print("veritabanına bağlandı");
         
        Statement komut = conn.createStatement();
           ResultSet rs= komut.executeQuery("Select * from kullanicilar where kullaniciTipi='mudur'");
           mudur_kadi.setText(rs.getString("kullanici_adi"));
           mudur_adi.setText(rs.getString("adi"));
           mudur_soyadi.setText(rs.getString("soyadi"));
           mudur_sifre.setText(rs.getString("sifre"));
           mudur_tel.setText(rs.getString("telefon"));
          conn.close();
          
        }
        catch(Exception hata) {
            JOptionPane.showMessageDialog(rootPane, hata.toString());
        }
    }
   private void guncellee(){
        try{
       
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        System.out.print("sürücü yüklendi");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/proje_rehberlik","root","");
         System.out.print("veritabanına bağlandı");

        Statement komut = conn.createStatement();
       
        String sorgu = "UPDATE kullanicilar SET kullanici_adi= '" 
            + mudur_kadi.getText() +
                "', sifre= '" 
            + mudur_sifre.getText() +
                "', adi= '" 
            + mudur_adi.getText() +
                "', soyadi= '" 
            + mudur_soyadi.getText() +
                "', telefon= '" 
            + mudur_tel.getText() +
                "' WHERE kullaniciTipi='mudur'";
         komut.executeUpdate(sorgu); //Sorgu cümlesindeki komutları icra et ve bilgileri Güncelle conn.close(); 
         JOptionPane.showMessageDialog(rootPane,"Başarıyla güncellendi..");
    
            conn.close();
            /*
            SqlCommand cmd2 = new SqlCommand("select [Kolon_Adi_1] from [Tablo_Adi] where [Kolon_Adi_2]=@veri2", cnn);
            cmd2.Parameters.AddWithValue("@veri2", "değeri");
            SqlDataReader dr = cmd2.ExecuteReader();
            if (dr.Read())
            {
                textBox1.Text = dr["Kolon_Adi"].ToString();
            }*/
            
            
        }
        catch(Exception hata){
           JOptionPane.showMessageDialog(rootPane, hata.toString());
            
        }
    }
    

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mudur_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mudur_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mudur_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mudur_ekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new mudur_ekrani().setVisible(true);
                
                
            }
            
        }
        )
                ;
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField mudur_adi;
    private javax.swing.JTextField mudur_kadi;
    private javax.swing.JTextField mudur_sifre;
    private javax.swing.JTextField mudur_soyadi;
    private javax.swing.JTextField mudur_tel;
    private javax.swing.JTextField rehber_adi;
    private javax.swing.JTextArea rehber_adres;
    private javax.swing.JTextField rehber_kadi;
    private javax.swing.JTable rehber_ogr_durum;
    private javax.swing.JTextField rehber_sifre;
    private javax.swing.JTextField rehber_soyadi;
    private javax.swing.JTextField rehber_tel;
    private javax.swing.JTextField rehberadi_ara;
    private javax.swing.JTable rehberlik_sonuclari;
    // End of variables declaration//GEN-END:variables

    private int mysql_num_rows(ResultSet rss2) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
